/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package my.spellcheckerguı;
import java.awt.Color;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;
import javax.swing.text.Highlighter.HighlightPainter;

/**
 *
 * @author Seçkin özdil
 */
public class SpellGUI extends javax.swing.JFrame  {
    JTextArea ta = new JTextArea (20, 30);
    ArrayList<String>wrongWords=new ArrayList<String>();
    ArrayList<String> suggestion = new ArrayList<String>();
    int clicked=0,size=0;
    String info = "",tmp="",tmp2="",s;
    File file;
    
    ArrayList<String>replaceList = new ArrayList<>();
    
    public static final String ALPHABET = "abcdefghijklmnopqrstuvwxyz";

    private static final ArrayList<String> edits(String word) {
    	
        ArrayList<String> result = new ArrayList<String>();
        // Deletion
        for (int i = 0; i < word.length(); ++i) {
            result.add(word.substring(0, i) + word.substring(i + 1));
        }
        // Transposition
        for (int i = 0; i < word.length() - 1; ++i) {
            result.add(word.substring(0, i) + word.substring(i + 1, i + 2) + word.substring(i, i + 1) + word.substring(i + 2));
        }
        // Alternation
        for (int i = 0; i < word.length(); ++i) {
            for (char c = ALPHABET.charAt(0); c <= ALPHABET.charAt(ALPHABET.length()-1); ++c) {
                result.add(word.substring(0, i) + String.valueOf(c) + word.substring(i + 1));
            }
        }
        // Insertion
        for (int i = 0; i <= word.length(); ++i) {
            for (char c = ALPHABET.charAt(0); c <= ALPHABET.charAt(ALPHABET.length()-1); ++c) {
                result.add(word.substring(0, i) + String.valueOf(c) + word.substring(i));
            }
        }
        return result;
    }

    public void suggest(String str) throws FileNotFoundException,IOException{
    	
		String sCurrentLine;

    	boolean hasGot=true;
    	
	 	FileReader in = new FileReader("dict.txt");
                BufferedReader br = new BufferedReader(in);
	    
		int count=0;
		String s="";
    	
    	while ((sCurrentLine = br.readLine()) != null) {
    
    		if(sCurrentLine.equalsIgnoreCase(str)){    		
    			count++;
    			s=str;
    			break;
    		}  		
    	}
    	in.close();
    	if(count==0){
                wrongWords.add(str);
    		suggestion=edits(str);
       			
    		for(int i=0;i<suggestion.size();i++){
    			
    			FileReader inn = new FileReader("dict.txt");
	    		BufferedReader brr = new BufferedReader(inn);
	    		String line = "at";
    			
    			boolean flag = false;
    			line = brr.readLine();
    			while(line != null){
    				
    			
		    		if(line.equalsIgnoreCase(suggestion.get(i))) {
		    			flag = true;
		    		}
		    		line = brr.readLine();
    			}
    			if( !flag) {
    				
    				suggestion.remove(i);
    				i--;
    			}
				inn.close();
    		}
    	for(int i=0;i<suggestion.size()-1;i++){
    		if(suggestion.get(i).equals(suggestion.get(i+1))){
    			suggestion.remove(i);
    			i--;
    		}
    	}
    		
    	//System.out.println(suggestion);
    	
    	}	
    	/*else{
    		System.out.println(s);
    	} */
    }
    public SpellGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setText("Ignore All");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setText("Ignore");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setText("Replace All");

        jButton4.setText("Replace");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(10);
        jTextArea1.setRows(5);
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(267, 267, 267))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(41, 41, 41)
                        .addComponent(jButton5)
                        .addGap(61, 61, 61)
                        .addComponent(jButton6)
                        .addGap(49, 49, 49)
                        .addComponent(jButton7)
                        .addContainerGap(227, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addGap(7, 7, 7)
                .addComponent(jButton3)
                .addGap(64, 64, 64))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Gözat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Check");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("               Spell Checker");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(45, 45, 45)
                        .addComponent(jButton2)))
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Gözat Butonu!!!!!!!!!!!
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         JFrame frame = new JFrame ("Display File");
         frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        
        JFileChooser chooser = new JFileChooser();

        int status = chooser.showOpenDialog (null);

        if (status != JFileChooser.APPROVE_OPTION)
           ta.setText ("No File Chosen");
        else
        {
           file = chooser.getSelectedFile();
           Scanner scan=null,scan2=null;
          try {
              scan = new Scanner (file);
              scan2= new Scanner(file);
          } catch (FileNotFoundException ex) {
            Logger.getLogger(SpellGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
          

         
         
         while (scan.hasNext()){
             info=scan.next();
               try {
                   suggest(info);
               } catch (IOException ex) {
                   Logger.getLogger(SpellGUI.class.getName()).log(Level.SEVERE, null, ex);
               }
         }
         info = "";
         
         while (scan2.hasNext()){
                
             info += scan2.nextLine() + "\n";       
         }
         
          ta.setText (info);
          String text= ta.getText().toUpperCase();
            
            Highlighter highlighter = ta.getHighlighter();
            
         HighlightPainter painter = 
                new DefaultHighlighter.DefaultHighlightPainter(Color.red);
         String tempp=null;
         for(int i=0;i<wrongWords.size();i+=1){
             tempp= wrongWords.get(i).toUpperCase();
         int p0 = 0;
         int p1 = 0;
                 p0=text.indexOf(tempp);
                 p1=p0+tempp.length();
             try {
                 highlighter.addHighlight(p0, p1, painter );
             } catch (BadLocationException ex) {
                 Logger.getLogger(SpellGUI.class.getName()).log(Level.SEVERE, null, ex);
             }
            
             
             
         }  
            
             

         
      }

      
      frame.getContentPane().add (ta);
      frame.pack();
      frame.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    	
        size=wrongWords.size();
        for(int k=0; k<=size;k++){
             try {
                 suggest(wrongWords.get(k));
             } catch (IOException ex) {
                 Logger.getLogger(SpellGUI.class.getName()).log(Level.SEVERE, null, ex);
             }
             
        for(int x=0;x<suggestion.size();x++){
         tmp2=tmp2+"\n"+suggestion.get(x);         
        }
        replaceList.add(tmp2);
        tmp2="";
             
        }
        
        jTextArea1.setText(replaceList.get(0));
        for(int a=wrongWords.size();a>size;a--){
            wrongWords.remove(a-1);
        }
        System.out.println(wrongWords.size()+" "+size);
        replaceList.remove(replaceList.size()-1);
        jFrame1.getContentPane().add (ta);
        jFrame1.pack();
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
//replace   
  
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int index=info.indexOf(wrongWords.get(clicked));
        ta.replaceRange(" ", index, index+wrongWords.get(clicked).length());
        ta.replaceRange(s+" ", index, index+wrongWords.get(clicked).length());
        //repaint();
        clicked++;
        if(replaceList.size()==clicked)
        jTextArea1.setText("SpellChecker completed press "+"\n"+" exit for quitting program.");
        else
        jTextArea1.setText(replaceList.get(clicked));
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        clicked++;
        if(replaceList.size()==clicked)
        jTextArea1.setText("SpellChecker completed press "+"\n"+" exit for quitting program.");
        else
        jTextArea1.setText(replaceList.get(clicked));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        jTextArea1.setText("SpellChecker completed press "+"\n"+" exit for quitting program.");
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked
        if(evt.getClickCount()==2)
        s=jTextArea1.getSelectedText();
        
    }//GEN-LAST:event_jTextArea1MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpellGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpellGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpellGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpellGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpellGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
